### ISSUE TITLE
مشکل در همراه اول

### ISSUE THREAD

**Issue by amijafi** [MiSaturo/Go-Warp-Scanner#2]
سلام
روی همراه اول بدون نتیجه و با کلی خطا مشابه شکل اسکن رو تمام میکنه
![Screenshot_20230611_104933_Termux](https://github.com/MiSaturo/Go-Warp-Scanner/assets/125953876/cc1e28b9-e7a6-44e7-8ecc-02603ccece50)

**Comment by MiSaturo** [comment]
اینا خطای اتصاله به udp معناش عدم امکان اتصاله به ip های در حال تسته و از کور کلش میاد

**Comment by amijafi** [comment]
خوب چاره اش چیه ؟ چون میدونیم که رو‌ همراه اول warp وصل میشه و مسیر بازه ، فقط اینجا نمیتونه ارتباط بگیره
